### ISSUE TITLE
Screenshot for Element?

### ISSUE THREAD

**Issue by suntong** [GoogleChromeLabs/pptraas.com#28]
Puppeteer also provides capability to do screenshot for a specific element -- https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlescreenshotoptions

Can pptraas.com do that someday?
Hope so. Thx.

**Comment by ebidel** [comment]
PRs welcome if you want to add it tot he screenshot handler.

**Comment by suntong** [comment]
Unfortunately I'm not a JS programmer and I don't know Puppeteer internal code.

**Comment by aslafy-z** [comment]
PR #42

**Comment by suntong** [comment]
me too, @ebidel.
