### ISSUE TITLE
EventEmitter memory leak detected. 11 exit listeners added

### ISSUE THREAD

**Issue by ernsheong** [GoogleChromeLabs/pptraas.com#36]
I've hit issue https://github.com/GoogleChrome/puppeteer/issues/594 using a modified endpoint from this repo. Did I do something wrong?

I added an endpoint to simply return the html content:
```js
app.get("/html", async (request, response) => {
  const url = request.query.url;
  if (!url) {
    return response.status(400).send("Please provide a URL. Example: ?url=https://example.com");
  }

  const browser = response.locals.browser;

  const page = await browser.newPage();
  const res = await page.goto(url, { waitUntil: "networkidle0" });
  const content = await page.content();

  response.status(res.status()).send(content);
  await browser.close();
});
```

Any idea how to address the `EventEmitter memory leak detected. 11 exit listeners added` warning, which led to the server being unresponsive eventually?

**Comment by ebidel** [comment]
- Are you catching errors and closing browser instances when there are errors?
- Did you try `process.setMaxListeners(Infinity)` as suggested?
- Did you try launching a single instance of chrome and reusing it across `/html` requests?

**Comment by ebidel** [comment]
Closing this as it's unrelated to the site itself.

**Comment by ernsheong** [comment]
Thanks for the pointers!
